# Generated by Django 5.2.6 on 2025-09-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0002_app_environment_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in-progress', 'In Progress')], default='in-progress', max_length=20)),
                ('helm_values', models.JSONField(default=dict)),
                ('logs', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='k8s.app')),
            ],
        ),
    ]
