# Generated by Django 5.2.6 on 2025-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0003_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='error_messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='logs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
