# Generated by Django 5.2.6 on 2025-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0004_deployment_error_messages_alter_deployment_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='helm_values',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
